package lk.greedaotest.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import lk.greedaotest.bean.Entity;

import lk.greedaotest.dao.EntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig entityDaoConfig;

    private final EntityDao entityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        entityDaoConfig = daoConfigMap.get(EntityDao.class).clone();
        entityDaoConfig.initIdentityScope(type);

        entityDao = new EntityDao(entityDaoConfig, this);

        registerDao(Entity.class, entityDao);
    }
    
    public void clear() {
        entityDaoConfig.getIdentityScope().clear();
    }

    public EntityDao getEntityDao() {
        return entityDao;
    }

}
